# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr

after_failure:
  "cat /home/travis/build/JimMcL/JUtils/JUtils.Rcheck/00check.log"

after_success:
  - Rscript -e 'library(covr); codecov()'
